apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seed-angular-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: seed-angular
    spec:
      containers:
      - name: seed-angular-pod
        image: systelab/seed-angular:latest
        env:
          - name: BACKEND
            value: "http://192.168.99.100:30002"
        ports:
        - containerPort: 80