apiVersion: v1
kind: Service
metadata:
  name: seed-angular-svc
  labels:
    app: seed-angular
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: seed-angular