apiVersion: v1
kind: Service
metadata:
  name: seed-jee-svc
  labels:
    app: seed-jee
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: seed-jee